# Generated by Django 4.0.1 on 2022-02-24 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_priority_task_status_report_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='last_report',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
